name: Trigger Sec Commit

on:
  workflow_run:
    workflows: ["Sec Commit"]
    types:
      - completed

jobs:
  trigger_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sec Commit Workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/your-username/your-repo/actions/workflows/Sec%20Commit/dispatches" \
            -d '{"ref":"main"}'
